version: "3.8"
services:
  mysql:
    image: mysql:8.0.30
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=carrot
      - MYSQL_USER=local
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  redis-cache:
    hostname: redis-cache
    container_name: redis-cache
    image: redis:alpine
    restart: always
    command: redis-server /etc/redis.conf
    volumes:
      - ./docker/config/redis_cache.cnf:/etc/redis.conf
    ports:
      - 6379:6379

  redis-session:
    hostname: redis-session
    container_name: redis-session
    image: redis:alpine
    restart: always
    command: redis-server /etc/redis.conf
    volumes:
      - ./docker/config/redis_session.cnf:/etc/redis.conf
    ports:
      - 6380:6380
