version: "3.8"
services:
  mysql:
    image: mysql:8.0.30
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=carrot
      - MYSQL_USER=local
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  redis-cache:
    hostname: redis-cache
    container_name: redis-cache
    image: redis:alpine
    restart: always
    command: redis-server /etc/redis.conf
    volumes:
      - ./docker/config/redis_cache.cnf:/etc/redis.conf
    ports:
      - "6379:6379"

  redis-session:
    hostname: redis-session
    container_name: redis-session
    image: redis:alpine
    restart: always
    command: redis-server /etc/redis.conf
    volumes:
      - ./docker/config/redis_session.cnf:/etc/redis.conf
    ports:
      - "6380:6380"

  redis-message:
    hostname: redis-message
    container_name: redis-message
    image: redis:alpine
    restart: always
    command: redis-server /etc/redis.conf
    volumes:
      - ./docker/config/redis_message.cnf:/etc/redis.conf
    ports:
      - "6381:6381"

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "notification_topic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
