### 1. 댓글 작성
POST {{ local-api }}/api/v1/posts/{{ postId }}/article
Authorization: Bearer {{ access_token }}
Content-Type: application/json

{
  "sentence": "댓글입니다."
}

### 2. 대댓글 작성
POST {{ local-api }}/api/v1/article/{{ articleId }}/reply
Authorization: Bearer {{ access_token }}
Content-Type: application/json

{
  "sentence": "대댓글입니다."
}

### 3. 댓글 수정
PUT {{ local-api }}/api/v1/article/{{ articleId }}
Authorization: Bearer {{ access_token }}
Content-Type: application/json

{
  "sentence": "댓글 수정입니다."
}

### 4. 대댓글 수정
PUT {{ local-api }}/api/v1/reply/{{ replyId }}
Authorization: Bearer {{ access_token }}
Content-Type: application/json

{
  "sentence": "대댓글 수정입니다."
}

### 5. 대댓글 삭제
DELETE {{ local-api }}/api/v1/article/{{ articleId }}
Authorization: Bearer {{ access_token }}


### 6. 대댓글 삭제
DELETE {{ local-api }}/api/v1/reply/{{ replyId }}
Authorization: Bearer {{ access_token }}

### 7. 댓글 조회
GET {{ local-api }}/api/v1/posts/{{ postId }}/article
Authorization: Bearer {{ access_token }}

### 8. 대댓글 조회
GET {{ local-api }}/api/v1/article/{{ articleId }}/reply
Authorization: Bearer {{ access_token }}
