### 게시물 등록
POST {{ local-api }}/api/v1/posts
Authorization: Bearer {{ access_token }}
Content-Type: application/json

{
  "title": "제목입니다.",
  "content": "내용입니다.",
  "price": 100000,
  "category": "디지털기기",
  "thumbnail": "tumbnail.com",
  "imageRequest": [
    {
      "imageUrl": "http://tumbnail.com/1",
      "originName": "사진1"
    },
    {
      "imageUrl": "http://tumbnail.com/2",
      "originName": "사진2"
    }
  ]
}


### 게시물 수정
PUT {{ local-api }}/api/v1/posts/{postId}
Authorization: Bearer {{ access_token }}
Content-Type: application/json

{
  "title": "제목입니다.",
  "content": "내용입니다.",
  "price": 100000,
  "category": "디지털기기",
  "thumbnail": "tumbnail.com",
  "imageRequest": [
    {
      "imageUrl": "http://tumbnail.com/1",
      "originName": "사진1"
    },
    {
      "imageUrl": "http://tumbnail.com/2",
      "originName": "사진2"
    }
  ]
}

### 게시물 삭제
DELETE {{ local-api }}/api/v1/posts/{postId}
Authorization: Bearer {{ access_token }}

### 게시물 예약
POST {{ local-api }}/api/v1/posts/{postId}/booked
Authorization: Bearer {{ access_token }}
Content-Type: application/json

{
  "bookerId" : "2L"
}


### 게시물 예약 취소
DELETE {{ local-api }}/api/v1/posts/{postId}/booked
Authorization: Bearer {{ access_token }}
