name: Pull Request 시 테스트 결과 반환

on:
  push:
    branches:
      - main
      - dev
    paths: 'backend/**'
  pull_request:
    branches:
      - main
      - dev
    paths: 'backend/**'
      
defaults:
  run:
    working-directory: ./backend

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      - name: make env file
        run: |
          cd ./src/main/resources

          touch ./application-oauth2.yml          
          echo "${{ secrets.OAUTH2 }}" >> ./application-oauth2.yml

        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: '**/build/test-results/test/TEST-*.xml'
